// <auto-generated />
using System;
using HealthStack.Catalog.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthStack.Catalog.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealthStack.Catalog.Api.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("093bec4a-006f-41b6-a594-e4f236563c3e"),
                            Description = "Health and nutrition supplements",
                            Name = "Supplements"
                        },
                        new
                        {
                            Id = new Guid("e978ea0e-68f1-4b62-928f-7034cd56ab7e"),
                            Description = "Personal hygiene and sanitation products",
                            Name = "Hygiene"
                        });
                });

            modelBuilder.Entity("HealthStack.Catalog.Api.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("78b983cb-d782-42ea-9eec-43b402463a56"),
                            Brand = "HealthPlus",
                            CategoryId = new Guid("093bec4a-006f-41b6-a594-e4f236563c3e"),
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Boosts immunity",
                            IsActive = true,
                            Name = "Vitamin C 500mg",
                            Price = 12.99m,
                            Sku = "HS1001"
                        },
                        new
                        {
                            Id = new Guid("813755d7-3f15-47a7-b479-908e281d69c3"),
                            Brand = "NutriLife",
                            CategoryId = new Guid("093bec4a-006f-41b6-a594-e4f236563c3e"),
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Supports heart and brain health",
                            IsActive = true,
                            Name = "Omega-3 Fish Oil",
                            Price = 19.50m,
                            Sku = "HS1002"
                        },
                        new
                        {
                            Id = new Guid("d7e749e9-f685-49f9-b855-b0a1684db9db"),
                            Brand = "SafeHands",
                            CategoryId = new Guid("e978ea0e-68f1-4b62-928f-7034cd56ab7e"),
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kills 99.9% germs",
                            IsActive = true,
                            Name = "Hand Sanitizer 250ml",
                            Price = 5.75m,
                            Sku = "HS1003"
                        });
                });

            modelBuilder.Entity("HealthStack.Catalog.Api.Models.Product", b =>
                {
                    b.HasOne("HealthStack.Catalog.Api.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HealthStack.Catalog.Api.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
